### ISSUE TITLE
no logs shipped

### ISSUE THREAD

**Issue by DaniSchenk** [logdna/logspout#14]
I'm trying to collect my Docker Container logs to logDNA, but I'm struggling. My `docker-compose.yml`:
```
version: "3"

services:
  logdna:
    image: logdna/logspout
    container_name: logdna
    restart: unless-stopped
    # ports:
      # - "127.0.0.1:5000:80"
    environment:
      - "LOGDNA_KEY=a692fc7xxxxx"
      - "FILTER_NAME=portainer_portainer_1"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
```
`docker-compose logs` prints:
```
logdna    | # logspout v3.2.6-custom by gliderlabs
logdna    | # adapters: raw syslog tcp udp logdna
logdna    | # options : persist:/mnt/routes
logdna    | # jobs    : http[logs,routes]:80 pump routes
logdna    | # routes  :
logdna    | #   ADAPTER ADDRESS CONTAINERS              SOURCES OPTIONS
logdna    | #   logdna          portainer_portainer_1           map[]
```
running `docker exec -it logdna logspout` prints:
```
[...]
2019/08/22 09:39:13 http[logs,routes]:80 ended: listen tcp 0.0.0.0:80: bind: address already in use
```
In my Onboarding Backend on https://app.logdna.com it's waiting for logs. I've tried setting a fixed localhost port in my `docker-compose.yml` but nothing changed. The `portainer/portainer` container is running on localhost only as well. I use a `traefik:v2.0` container as a nginx proxy which is using port 80 and 443. Can somebody help me?
